# Generated by Django 3.1.5 on 2021-02-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customeraccounts',
            fields=[
                ('account_num', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('account_type', models.CharField(max_length=20)),
                ('balance', models.FloatField()),
                ('nominee', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customeraccounts')),
            ],
        ),
    ]
