# Generated by Django 3.1.5 on 2021-02-25 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210224_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccounts',
            name='balance',
            field=models.FloatField(default=1000.0, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
    ]
