# Generated by Django 3.1.5 on 2021-02-27 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210225_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='accounttransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('deposit_acc_num', models.CharField(max_length=5)),
                ('amount_debit', models.FloatField()),
                ('amount_credit', models.FloatField()),
                ('curr_bal', models.FloatField()),
                ('with_acc_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customeraccounts')),
            ],
        ),
    ]
