# Generated by Django 3.1.5 on 2021-02-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_accounttransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounttransaction',
            old_name='with_acc_num',
            new_name='pri_acc_num',
        ),
        migrations.RenameField(
            model_name='accounttransaction',
            old_name='deposit_acc_num',
            new_name='sec_acc_num',
        ),
    ]
