# Generated by Django 3.1.5 on 2021-02-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20210227_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttransaction',
            name='amount_credit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='accounttransaction',
            name='amount_debit',
            field=models.FloatField(default=0),
        ),
    ]
